name: Tiger
version: 0.1.0.0
github: "ksrky/Tiger"
license: BSD3
author: "ksrk"
maintainer: "example@example.com"
copyright: "2022 ksrk"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ksrky/Tiger#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - containers
  - haskeline
  - hspec
  - mtl
  - prettyprinter
  - text
  - vector

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

library:
  source-dirs: src

executables:
  chap2:
    main: Main.hs
    source-dirs: src/chap2
  chap3:
    main: Main.hs
    source-dirs: src/chap3
